# Generated by Django 6.0.2 on 2026-02-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="patient_type",
            field=models.CharField(
                choices=[
                    ("EMERGENCY", "Emergency"),
                    ("SENIOR", "Senior Citizen"),
                    ("NORMAL", "Normal"),
                ],
                default="NORMAL",
                max_length=20,
            ),
        ),
    ]
