# Generated by Django 6.0.2 on 2026-02-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_passwordresetotp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="passwordresetotp",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="passwordresetotp",
            name="resend_available_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
