# Generated by Django 6.0.2 on 2026-02-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_passwordresetotp_attempt_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="total_appointments",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="total_cancellations",
            field=models.IntegerField(default=0),
        ),
    ]
