# Generated by Django 6.0.2 on 2026-02-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_is_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("DOCTOR", "Doctor"),
                    ("PATIENT", "Patient"),
                ],
                default="ADMIN",
                max_length=10,
            ),
        ),
    ]
