# Generated by Django 6.0.2 on 2026-02-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_user_phone_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="patient_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EMERGENCY", "Emergency"),
                    ("SENIOR", "Senior Citizen"),
                    ("NORMAL", "Normal"),
                ],
                default="NORMAL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(default=0, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("DOCTOR", "Doctor"),
                    ("PATIENT", "Patient"),
                ],
                default="PATIENT",
                max_length=10,
            ),
        ),
    ]
