# Generated by Django 6.0.2 on 2026-02-11 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appointment_created_at_timeslot_locked_by_and_more"),
        ("doctors", "0002_remove_doctor_is_active_doctor_is_available_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority_score", models.IntegerField()),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-priority_score", "requested_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "status"], name="appointment_doctor__0653d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["doctor", "date"], name="appointment_doctor__05e5a9_idx"
            ),
        ),
        migrations.AddField(
            model_name="appointmentqueue",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="appointmentqueue",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waiting_queue",
                to="appointments.timeslot",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointmentqueue",
            unique_together={("slot", "patient")},
        ),
    ]
