# Generated by Django 6.0.2 on 2026-02-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_appointmentqueue_alter_appointment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentqueue",
            name="admin_override",
            field=models.BooleanField(default=False),
        ),
    ]
