# Generated by Django 6.0.2 on 2026-02-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_doctor_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="email",
        ),
    ]
